### ISSUE TITLE
DMA based CRC may yield performance improvement

### ISSUE THREAD

**Issue by going-digital** [rscott2049/pico-rmii-ethernet_nce#1]
Great project! 100Mbps is really impressive. I notice you're using a table based CRC. It may be worth switching from CPU to using the CRC feature of the DMA, particularly as you can include a memcpy with `channel_config_set_read/write_increment()` and handle circular buffers with `channel_config_set_ring()`.

[Example CRC code here that doesn't include the memcpy.](https://github.com/raspberrypi/pico-examples/blob/master/dma/sniff_crc/sniff_crc.c)

Happy to code this up and benchmark, once my dev hardware arrives.

**Comment by rscott2049** [comment]
Thanks for the comment! In fact, I am just now debugging a replacement for the copy to/from LWIP buffer routines that uses the sniffer, just for completeness. The project I originally intended to use this on (DECstation2040) already uses the sniffer to do PSRAM address calculations for video line fetches, so it won't benefit. (But the DECstation2350 should be able to!)

I'll keep this issue opened until DMA sniffer support is checked in...

**Comment by rscott2049** [comment]
So the new code works, except for a nasty bug that only shows up when doing large ping tests. The iperf results are pretty amazing:
  SRAM:
MHz Iperf MBits/sec 
300 94.9
250 94.9
200 94.9
150 94.9
100 54.4, CRC errors 

Flash:
300 94.9
250 94.9
200 94.9
150 78.4
100 marginal link

Unfortunately, I'm busy with other work, so haven't had time to fix the nasty bug...

**Comment by going-digital** [comment]
Wow! That's huge. Thanks for putting in the work. I'm expecting test hardware to arrive next week, so I can help out tracking down bugs then if that helps.

**Comment by rscott2049** [comment]
Fixed the bug! New code checked in. Will be working on porting to RP2350 to see how the new chip affects performance.
